### ISSUE TITLE
墓碑在水中失效

### ISSUE THREAD

**Issue by william-song-shy** [plusls/plusls-carpet-addition#10]
头颅无法含水

**Comment by plusls** [comment]
Emmmm有没有具体一点的描述呢，是指它不会生成在水里还是它生成在水里却没有水

**Comment by william-song-shy** [comment]
> Emmmm有没有具体一点的描述呢，是指它不会生成在水里还是它生成在水里却没有水

复现：在水中溺死，由于头颅不能含水，所以会掉落，但物品就没了

**Comment by ch-yx** [comment]
是的。要是在水/岩浆里溺死，头会被立刻破坏。
事实上，如果墓碑被玩家挖掘以外的方式被破坏，和普通的头没有区别。
甚至可以用来刷头。

**Comment by plusls** [comment]
思考了一下，现在墓碑不会被水流破坏，但是如果它被tnt炸掉则会掉落头颅
并且我打算把这个当作特性，作为获取头颅的一种方式
