### ISSUE TITLE
Game crash upon launch

### ISSUE THREAD

**Issue by chris819t** [plusls/plusls-carpet-addition#13]
Ive tried with and without your Carpet Addition mod and it works without it but when I add it to my mods list it crashes when I launch the game. Here is the latest.log after it crashes and i would provide a crash report but after looking for the latest crash after it happens it doesn't appear to create a report for that specific crash.
https://pastebin.com/byPmWUTh

**Comment by plusls** [comment]
can you upload your mod pack?

**Comment by chris819t** [comment]
Well it's not really a modpack more of a list of mods that I choose to use.

**Comment by plusls** [comment]
I means pack your mods dir.

**Comment by chris819t** [comment]
here is a link to a zip file of all the mods I use. It should work https://drive.google.com/file/d/1Ou8zZ4aXS0G51CuNmUif4Z2JyzuPOfu7/view?usp=sharing

**Comment by chris819t** [comment]
were you able to find the issue?

**Comment by plusls** [comment]
I can't access...
I need your accept

**Comment by plusls** [comment]
I think you can upload it to github
![image](https://user-images.githubusercontent.com/23459592/141938763-52666883-b243-4656-9533-cac98cbf9760.png)

**Comment by chris819t** [comment]
It wont let me upload those types of files. It will mainly only let me upload image files

Try this link instead https://drive.google.com/file/d/1Ou8zZ4aXS0G51CuNmUif4Z2JyzuPOfu7/view?usp=sharing

**Comment by plusls** [comment]
> It wont let me upload those types of files. It will mainly only let me upload image files

You can upload .tar.gz
or rename file ends with .gz

**Comment by chris819t** [comment]
Rename it from being what? renaming the folder containing the mods does nothing. Im not familiar with that file type so idk what im doing

**Comment by plusls** [comment]
Oh, I can access it now, I will view it tomorrow

**Comment by chris819t** [comment]
Ok. Thank you.
Good because i figured it out but it still says "not included in the list" even though its a GZ file type

**Comment by plusls** [comment]
It no crash in my client, but I show many log
![image](https://user-images.githubusercontent.com/23459592/142222861-48018128-8691-46f1-91a6-ba8a369c14fb.png)

**Comment by chris819t** [comment]
?? well its still crashing for me. I tried without "cool elytra" and its still doing it so it cant because of that

**Comment by chris819t** [comment]
Are you using the Fabric Loader version 0.11.6-1.16.5? Thats the loader im using

**Comment by chris819t** [comment]
Hello?

**Comment by plusls** [comment]
I am sorry I forgot reply you 
I use fabric loadee 0.11.6 and load the optifabric, and it works for me.

May be you can upload your config folder？

**Comment by plusls** [comment]
Since I am busy with my studies recently, I may not be able to reply in time, please forgive me

**Comment by plusls** [comment]
Or you can pm me in discorddiscord
plusls#3759

**Comment by chris819t** [comment]
https://drive.google.com/drive/folders/1VnH119bSC44y0qBKtTzryc9aiGDMlHaq?usp=sharing
There is the link to my config file. There might be files in there to mods i'm not using.
I also added you on Discord because I couldn't do a search for you, it said there was no results.
