### ISSUE TITLE
Incompatibility with Johan Carpet Addition

### ISSUE THREAD

**Issue by ZuccySuccy** [plusls/plusls-carpet-addition#14]
Game fails to load when [Johan Carpet](https://github.com/JohanVonElectrum/Johan-Carpet) is in the mods  folder. This is with the most recent versions of both mods along with carpet and a recent version of FAP
[latest.log](https://github.com/plusls/plusls-carpet-addition/files/7699932/latest.log)
I'm not sure which mod is the actual issue, so I'm essentially making the same report on both github pages

**Comment by plusls** [comment]
avoidAnvilTooExpensive conflict
It will fix in next version

**Comment by JohanVonElectrum** [comment]
If you are working on this, please note this commit: https://github.com/JohanVonElectrum/Johan-Carpet/commit/75403d4bd4293acf3793db4291dcf5bd70fbe754#diff-927cd640b5904705a812b33949c5b99339b653190e2b25a7eaf66d3e0e81ff4a
