### ISSUE TITLE
无法启动游戏

### ISSUE THREAD

**Issue by unrealmanchen** [plusls/plusls-carpet-addition#17]
### Minecraft Version

1.18.1

### Plusls Carpet Addition Version

plusls-carpet-addition-1.18.1-0.2.4

### Carpet Version

fabric-carpet-1.18.1-1.4.57+v220119

### Fabric API Version

fabric-api-0.46.2+1.18

### Description

[minecraft-exported-logs-2022-02-21T10-36-24.log](https://github.com/plusls/plusls-carpet-addition/files/8105742/minecraft-exported-logs-2022-02-21T10-36-24.log)

### To Reproduce

启动游戏即可享受高血压

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by plusls** [comment]
能上传你的 mods 目录吗？

**Comment by plusls** [comment]
我怀疑是因为没安装 fabric api？

**Comment by unrealmanchen** [comment]
<img width="453" alt="截屏2022-02-21 下午4 08 20" src="https://user-images.githubusercontent.com/67812862/154913569-f914eb87-f811-40bc-9a23-cb56aaffd15e.png">

**Comment by plusls** [comment]
你要不去 curseforge 下一个新的 api 试试 https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by unrealmanchen** [comment]
解决了 看来是api的锅
感谢！
