### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by foxmaid** [plusls/plusls-carpet-addition#19]
### Minecraft Version

1.18.2

### Plusls Carpet Addition Version

0.2.4

### Carpet Version

1.4.66

### Fabric API Version

0.48.0

### Description

1.18.2能启动游戏但是进存档闪退

### To Reproduce

1.18.2能启动游戏但是进存档闪退

### Log

[minecraft-exported-logs-2022-03-19T22-29-13.log](https://github.com/plusls/plusls-carpet-addition/files/8309417/minecraft-exported-logs-2022-03-19T22-29-13.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请尝试使用 [CI#177](https://github.com/plusls/plusls-carpet-addition/actions/runs/1931993619) 版本，若问题依然存在请再次上传日志。

**Comment by foxmaid** [comment]
可以了
