### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by icewolf-li** [plusls/plusls-carpet-addition#20]
### What new features do you want?

光灵箭强制补货很好，但是会导致村民涨价，可否通过换种方式，或者禁止村民涨价，用的是1.18.1

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by plusls** [comment]
emm 才看到
可以用发射器射呀，而且有袭击塔绿宝石完全不缺把

**Comment by icewolf-li** [comment]
的确，我改用发射器了，绿宝石是不缺，只是一次只用放一组在背包，涨价就要放好几组在背包占位置
