### ISSUE TITLE
[Bug] Can't convert dirt to mud in 1.19

### ISSUE THREAD

**Issue by kosma** [plusls/plusls-carpet-addition#21]
### Minecraft Version

1.19

### Plusls Carpet Addition Version

1.19-0.2.5-beta+1703874

### Carpet Version

1.19-1.4.79+v220607

### Fabric API Version

0.56.0+1.19

### Description

In the 1.19 branch, the mod makes it unable to convert dirt into mud using a water bottle. The reason is that you `@Override` the method in the mixin, which is considered very naughty and you will be getting coal for Christmas. The Minecraft Commitee for Good Mixins suggests you use `@Inject` instead. :p 

### To Reproduce

Run the 1.19 branch, rightclick a dirt block with a water bottle. (In my setup, PCA was on the server)

### Expected behavior

Dirt turns into mud.

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Try this version [0.2.5-beta+38c6228](https://github.com/plusls/plusls-carpet-addition/suites/7211679176/artifacts/288693929).

**Comment by kosma** [comment]
Thanks!
