### ISSUE TITLE
[Feature Request] support 1.19.3

### ISSUE THREAD

**Issue by Notoriousi** [plusls/plusls-carpet-addition#34]
### What new features do you want?

The mod does not work on the newest version 1.19.3

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Hendrix-Shen** [comment]
Try this version: [1.19.3-0.2.5-beta+5fa8bc5](https://github.com/plusls/plusls-carpet-addition/suites/9807414652/artifacts/471949573).
