### ISSUE TITLE
[Bug] 1.19.2服务端无法使用

### ISSUE THREAD

**Issue by l666685** [plusls/plusls-carpet-addition#35]
### Minecraft Version

MCServer1.19.2-fabric

### Plusls Carpet Addition Version

plusls-carpet-addition-1.19-0.2.5-alpha+1703874

### Carpet Version

 fabric-carpet-1.19.2-1.4.84+v221018

### Fabric API Version

fabric-api-0.70.0+1.19.2

### Description

加入这个mod后，mcFabric服务端就会崩溃
不知道为啥

### To Reproduce

emm
这是一个链接
里边是bug_mcServer
运行就行
链接: https://pan.baidu.com/s/1GQtEMuLMdAh8qDQ1SwiN8A?pwd=1234 (抱歉,我目前只找到百度网盘可以上传)

### Expected behavior

正常启动服务器

### Log

[2022-12-31-7.log](https://github.com/plusls/plusls-carpet-addition/files/10327518/2022-12-31-7.log)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
MC 1.19.2 请使用此处提供的版本。
https://hendrixshen.lanzouy.com/b0c4srcti 密码:plusls

**Comment by l666685** [comment]
谢谢
QWQ
