### ISSUE TITLE
[Bug] 1.19.2 安装Mod后无法启动

### ISSUE THREAD

**Issue by GITHUB-Leo-LOL** [plusls/plusls-carpet-addition#36]
### Minecraft Version

1.19.2

### Plusls Carpet Addition Version

plusls-carpet-addition-1.19-0.2.5-alpha+1703874

### Carpet Version

1.4.83+v220727

### Fabric API Version

0.70.0

### Description

在只安装了上面3个Mod后启动显示Mod注入失败

### To Reproduce

如上

### Log

[错误报告-2023-1-3_13.40.49.zip](https://github.com/plusls/plusls-carpet-addition/files/10334513/-2023-1-3_13.40.49.zip)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
与 #35 重复。

**Comment by GITHUB-Leo-LOL** [comment]
谢谢
