### ISSUE TITLE
地毯指令需要4级OP权限无效

### ISSUE THREAD

**Issue by xingchen-Forever** [plusls/plusls-carpet-addition#47]
### What new features do you want?

在地毯中，有一条规则可以控制指令权限等级，如下图
![image](https://github.com/plusls/plusls-carpet-addition/assets/76945134/25998720-747a-4067-89fc-e6c6a4c20b52)
如果我设置4级，那么拥有2级op的玩家不能执行/carpet相关指令
但是这对于PCA无效（/pca依然可以被任意级别op执行），也未在PCA找到替代指令，希望可以改进，谢谢

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by Crystal0404** [comment]
PCA使用了Magiclib的settingManager来管理，它并不由Carpet管理。请使用```/magiclib settingManagerLevel```

**Comment by xingchen-Forever** [comment]
好的
