### ISSUE TITLE
Crash report while using PlusIscarpet with 1.17.1 version, and i am using this build  plusls-carpet-addition-1.17.1-0.1.9.jar

### ISSUE THREAD

**Issue by Lokemol** [plusls/plusls-carpet-addition#6]
this is the crash report i get 
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 8/30/21, 11:27 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: categories
	at com.plusls.carpet.PcaMod.lambda$onGameStarted$0(PcaMod.java:56)
	at carpet.settings.SettingsManager.lambda$notifyRuleChanged$0(SettingsManager.java:197)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at carpet.settings.SettingsManager.notifyRuleChanged(SettingsManager.java:197)
	at carpet.settings.ParsedRule.set(ParsedRule.java:176)
	at carpet.settings.ParsedRule.set(ParsedRule.java:133)
	at carpet.settings.SettingsManager.loadConfigurationFromConf(SettingsManager.java:410)
	at carpet.settings.SettingsManager.attachServer(SettingsManager.java:121)
	at carpet.CarpetServer.onServerLoaded(CarpetServer.java:87)
	at net.minecraft.server.MinecraftServer.handler$cbd000$serverLoaded(MinecraftServer.java:8291)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java)
	at net.minecraft.class_3176.method_3823(class_3176.java:184)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 363792424 bytes (346 MiB) / 1073741824 bytes (1024 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37564.63
	Virtual memory used (MB): 12275.19
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms1024M -Xmx10240M
	Fabric Mods: 
		aegis: Aegis 3.0.0
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.4.25
		betterthanmending: BetterThanMending 1.3.0
		blue_endless_jankson: jankson 1.2.1
		carpet: Carpet Mod 1.4.45
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.21.1+build.650
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		deepslatecutting: Deepslate Cutting 1.2.0
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		easy_painter: Easy Painter 1.0.2
		ekho: Ekho 0.2.0
		fabric: Fabric API 0.38.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.12+3fe74aa118
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.0+3fe74aa118
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+8195aec118
		fabricloader: Fabric Loader 0.11.6
		fallingtree: FallingTree 2.13.0
		ferritecore: FerriteCore 3.0.2
		flan: Flan 1.17.1-1.6.1
		flytre_lib: FlytreLib 0.2.21
		grindenchantments: Grind Enchantments 1.2.1+1.17
		harvest: Harvest 1.2.12
		hydrogen: Hydrogen 0.3
		inmis: Inmis 2.3.1-1.17
		inventorysorter: Inventory Sorter 1.7.9-1.17
		java: Java HotSpot(TM) 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.4
		minecraft: Minecraft 1.17.1
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		ne-v-seti: Ne v seti 0.1.6-1.17
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		pca: Plusls carpet addition mod 1.17.1-0.1.9
		perfectaccuracy: Perfect Accuracy 1.1
		playtime-tracker: Playtime Tracker 0.1.2
		recipecache: recipecache 0.2.0-1.17.1
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		server_translations_api: Server Translations API 1.4.4+1.17
		servux: Servux 0.1.0
		sgui: SGui 1.0.0-pre0-1.17-pre1
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		syncmatica: Syncmatica 0.2.6
		ticktools: TickTools 1.0.0
		worldspecificviewdistance: World Specific View Distance 0.1.0-1.17
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
	Player Count: 0 / 7; []
	Data Packs: vanilla, file/Back to blocks.zip, file/Charcoal to dye.zip, file/More Bricks.zip, file/Straight to shapeless.zip, file/armored elytra v1.0.3.zip, file/classic fishing loot v1.1.0.zip, file/coal to black dye.zip, file/craftable notch apples.zip, file/double slabs.zip, file/dragon drops v1.3.0.zip, file/graves v2.8.4.zip, file/larger phantoms v1.2.1.zip, file/more bark.zip, file/more stairs.zip, file/more trapdoors.zip, file/nether portal coords v1.1.0.zip, file/powder to glass.zip, file/universal dyeing.zip, file/unpackable ice.zip, file/unpackable nether wart.zip, file/villager death messages v1.2.1.zip, file/villager workstation highlights v1.1.0.zip, file/snowy.zip, Fabric Mods, file/Infinite Trades.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by plusls** [comment]
Because carpet change the type of categories.

And I fix it in new commit, you can try build in github action.

Because I still have some new features that I haven’t implemented, I haven't released new version.
