### ISSUE TITLE
CarefulBreak crashes the game sometimes

### ISSUE THREAD

**Issue by Lokemol** [plusls/plusls-carpet-addition#7]
**Well, i am using build 1.17.1 version 0.2.0 and when i try to careful break sometimes this crash happens i find.

I find the solution to this problem doing /subscribe  carefulbreak to disable it and then do it again to enable it, this fixes the problem, but well, its a bug, that is kind of annoying since it causes a crash in your game, i am playing on a fabric server, thanks :D**
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 9/1/21, 2:45 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3816()" because "carpet.CarpetServer.minecraft_server" is null
	at essentialaddons.helpers.SubscribeData.getFile(SubscribeData.java:41)
	at essentialaddons.helpers.SubscribeData.writeSaveFile(SubscribeData.java:64)
	at net.minecraft.class_2248.handler$cjk000$onBreak(class_2248.java:3672)
	at net.minecraft.class_2248.method_9576(class_2248.java)
	at net.minecraft.class_2480.method_9576(class_2480.java:148)
	at net.minecraft.class_636.method_2899(class_636.java:125)
	at net.minecraft.class_636.method_2902(class_636.java:250)
	at net.minecraft.class_310.method_1590(class_310.java:1553)
	at net.minecraft.class_310.method_1508(class_310.java:1911)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at essentialaddons.helpers.SubscribeData.getFile(SubscribeData.java:41)
	at essentialaddons.helpers.SubscribeData.writeSaveFile(SubscribeData.java:64)
	at net.minecraft.class_2248.handler$cjk000$onBreak(class_2248.java:3672)
	at net.minecraft.class_2248.method_9576(class_2248.java)
	at net.minecraft.class_2480.method_9576(class_2480.java:148)
	at net.minecraft.class_636.method_2899(class_636.java:125)
	at net.minecraft.class_636.method_2902(class_636.java:250)
	at net.minecraft.class_310.method_1590(class_310.java:1553)
	at net.minecraft.class_310.method_1508(class_310.java:1911)

-- Affected level --
Details:
	All players: 1 total; [class_746['Lokemol'/1764703, l='ClientLevel', x=660.97, y=115.00, z=1313.69]]
	Chunk stats: 4096, 1225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,70,96), Section: (at 0,6,0 in -13,4,6; chunk contains blocks -208,0,96 to -193,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 56988236 game time, 61398812 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks 1.17.1.zip, cullleaves/smartleaves, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 634649240 bytes (605 MiB) / 1308622848 bytes (1248 MiB) up to 19327352832 bytes (18432 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37564.63
	Virtual memory used (MB): 18999.59
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 33.71
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx18G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.4.25
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 2.0.1
		betterthanmending: BetterThanMending 1.3.0
		betterthirdperson: Better Third Person 1.5.0
		blue_endless_jankson: jankson 1.2.1
		carpet: Carpet Mod 1.4.45
		carpet-autocraftingtable: Carpet-AutoCraftingTable 1.4.35
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.21.1+build.650
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		customsplashscreen: Custom Splash Screen 1.1.0
		deepslatecutting: Deepslate Cutting 1.2.0
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		entityculling: EntityCulling-Fabric 1.3.3
		essentialaddons: Essential Addons 1.17.1-1.0.3
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabricloader: Fabric Loader 0.11.6
		fallingtree: FallingTree 2.13.0
		ferritecore: FerriteCore 3.0.3
		flytre_lib: FlytreLib 0.2.21
		gbfabrictools: GBfabrictools 1.3.4+1.17
		grindenchantments: Grind Enchantments 1.2.1+1.17
		hydrogen: Hydrogen 0.3
		indium: Indium 1.0.0+mc1.17.1
		inmis: Inmis 2.3.1-1.17
		inventoryhud: Inventory HUD + 3.3.2
		inventorysorter: Inventory Sorter 1.7.9-1.17
		iris: Iris 1.1.2-starline+build.492
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: OpenJDK 64-Bit Server VM 16
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.4
		malilib: MaLiLib 0.10.0-dev.24
		minecraft: Minecraft 1.17.1
		minihud: MiniHUD 0.19.0-dev.20210707.150016
		minitweaks: MiniTweaks 1.1.2
		modmenu: Mod Menu 2.0.6
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		no_fog: No Fog 1.1.0+1.17.1
		noexpensive: NoExpensive 1.17-Fabric-1.2.0
		notes: Notes 1.0.7
		offlineskins: OfflineSkins 1.17.1-v1-fabric
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		pca: Plusls carpet addition mod 1.17.1-0.2.0
		perfectaccuracy: Perfect Accuracy 1.1
		recipecache: recipecache 0.2.0-1.17.1
		replaymod: Replay Mod 1.17.1-2.6.1
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		sheepconsistency: Sheep Consistency 1.0.3
		sodium: Sodium 0.3.2+IRIS2-build.130
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		syncmatica: Syncmatica 0.2.6
		xaerominimap: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.17.0
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks 1.17.1.zip, cullleaves/smartleaves
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Comment by plusls** [comment]
It is not my fault, it crash because here

https://github.com/Super-Santa/EssentialAddons/blob/da32a039d0b6742dd9f2f84c3612aa4164888de2/src/main/java/essentialaddons/helpers/SubscribeData.java#L49

The `CarpetServer.minecraft_server` is null so your game crash.

I think you should report this crash to 

https://github.com/Super-Santa/EssentialAddons/issues

**Comment by Lokemol** [comment]
OMG i am sorry, i posted this on the incorrect github, pardon me, PlusIs, i am sorry 👍
